# SITE CONFIGURATION
url: "https://rustyonrampage.github.io/"
baseurl: ""

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Text Mining Backyard
  avatar: assets/img/rickavatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "It's a blog  about gathering text data, exploring and processing it, and eventually making sense of it effectively." # used by search engines

  # Header and footer text
  header_text: >
     <strong> Hello World! </strong>

     <p>It's a blog  about gathering text data, exploring and processing it, and eventually making sense of it effectively.</p>
  header_text_feature_image:
  footer_text: >
   Happy Coding <i class="fa fa-smile-o" aria-hidden="true"></i>

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "rustyonrampage"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "rustyonrampage"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-109430592-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: rustyonrampage
  comments: true # for disques
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
input: GFM
highlighter: rouge
syntax_highlighter_opts:
  # Rouge Options › https://github.com/jneen/rouge#full-options
  css_class: 'highlighter-rouge'
  #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
  span:
    line_numbers: false
  block:
    line_numbers: true
    start_line: 1
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate , jekyll-sitemap]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
  # - vendor/bundle
  
